spring.application.name=cbs
# Conexión al servidor Discovery
eureka.client.serviceUrl.defaultZone=http://localhost:8762/eureka
spring.datasource.url=jdbc:postgresql://localhost:5432/db_nexus_cbs
spring.datasource.username=postgres
spring.datasource.password=12345

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port=9093
