# --- Identidad del Microservicio ---
server.port=9095
spring.application.name=ms-geografia

# --- Conexión a Eureka ---
eureka.client.serviceUrl.defaultZone=http://localhost:8762/eureka

# --- Base de Datos (CORREGIDO: BD Independiente) ---
spring.datasource.url=jdbc:postgresql://localhost:5432/db_nexus_geografia
spring.datasource.username=postgres
spring.datasource.password=12345

# --- JPA / Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# NOTA: Se eliminó la línea de 'default_schema' para mantener consistencia 
# con los otros microservicios.